FirmaTransportowa/FirmaTransportowa/FirmaTransportowa/Controllers/RaportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DomainModel;
using TransportDB;
using FirmaTransportowa.Models;
using Microsoft.AspNet.Identity;
using System.Globalization;

namespace FirmaTransportowa.Controllers
{
    public class RaportsController : Controller
    {
        private TransportDBContext db = new TransportDBContext();
        private ApplicationDbContext identityDb = new ApplicationDbContext();

        // GET: Raports
        public ActionResult Index()
        {
            return View(db.Raports.ToList());
        }

        // GET: Raports/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Raport raport = db.Raports.Find(id);
            if (raport == null)
            {
                return HttpNotFound();
            }
            return View(raport);
        }

        // GET: Raports/Create
        public ActionResult Create()
        {
            var routesList = db.Routes.OrderBy(u => u.Name).ToList().Select(uu =>
            new SelectListItem { Value = uu.Name.ToString(), Text = uu.Name }).ToList();
            ViewBag.Routes = routesList;

            return View();
        }

        // POST: Raports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PassengersNumber,FuelCost,Distance")] Raport raport, string date, string Trasa)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                var driverName = identityDb.Users.Where(x => x.Id == userId).FirstOrDefault().FirstName + " "
                    + identityDb.Users.Where(x => x.Id == userId).FirstOrDefault().LastName;
                DateTime finalDate = DateTime.ParseExact(date, "dd-MM-yyyy H:mm", CultureInfo.InvariantCulture);

                raport.Date = finalDate;
                raport.RouteName = Trasa;
                raport.DriverId = driverName; 
                db.Raports.Add(raport);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(raport);
        }

        // GET: Raports/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Raport raport = db.Raports.Find(id);
            if (raport == null)
            {
                return HttpNotFound();
            }
            return View(raport);
        }

        // POST: Raports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PassengersNumber,FuelCost,Distance,DriverId")] Raport raport)
        {
            if (ModelState.IsValid)
            {
                db.Entry(raport).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(raport);
        }

        // GET: Raports/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Raport raport = db.Raports.Find(id);
            if (raport == null)
            {
                return HttpNotFound();
            }
            return View(raport);
        }

        // POST: Raports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Raport raport = db.Raports.Find(id);
            db.Raports.Remove(raport);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FirmaTransportowa/FirmaTransportowa/FirmaTransportowa/Controllers/RolesController.cs
using FirmaTransportowa.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirmaTransportowa.Controllers
{
    public class RolesController : Controller
    {
        public ActionResult Index()
        {
            // Populate Dropdown Lists
            var context = new ApplicationDbContext();

            var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>
            new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = rolelist;

            var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
            new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userlist;

            ViewBag.Message = "";

            return View();
        }


        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {

            try
            {
                var context = new ApplicationDbContext();
                context.Roles.Add(new Microsoft.AspNet.Identity.EntityFramework.IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                context.SaveChanges();
                ViewBag.Message = "Role created successfully !";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(string RoleName)
        {
            var context = new ApplicationDbContext();
            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Roles/Edit/5
        public ActionResult Edit(string roleName)
        {
            var context = new ApplicationDbContext();
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            return View(thisRole);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Microsoft.AspNet.Identity.EntityFramework.IdentityRole role)
        {
            try
            {
                var context = new ApplicationDbContext();
                context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        //  Adding Roles to a user
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RoleAddToUser(string UserName, string RoleName)
        {
            var context = new ApplicationDbContext();

            if (context == null)
            {
                throw new ArgumentNullException("context", "Context must not be null.");
            }

            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);
            userManager.AddToRole(user.Id, RoleName);


            ViewBag.Message = "Role created successfully !";

            // Repopulate Dropdown Lists
            var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = rolelist;
            var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
            new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userlist;

            return View("Index");
        }


        //Getting a List of Roles for a User
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles(string UserName)
        {
            if (!string.IsNullOrWhiteSpace(UserName))
            {
                var context = new ApplicationDbContext();
                ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

                var userStore = new UserStore<ApplicationUser>(context);
                var userManager = new UserManager<ApplicationUser>(userStore);
                ViewBag.RolesForThisUser = userManager.GetRoles(user.Id);


                // Repopulate Dropdown Lists
                var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
                ViewBag.Roles = rolelist;
                var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
                new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
                ViewBag.Users = userlist;
                ViewBag.Message = "Roles retrieved successfully !";
            }

            return View("Index");
        }

        //Deleting a User from A Role
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser(string UserName, string RoleName)
        {
            var account = new AccountController();
            var context = new ApplicationDbContext();
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);


            if (userManager.IsInRole(user.Id, RoleName))
            {
                userManager.RemoveFromRole(user.Id, RoleName);
                ViewBag.Message = "Role removed from this user successfully !";
            }
            else
            {
                ViewBag.Message = "This user doesn't belong to selected role.";
            }

            // Repopulate Dropdown Lists
            var rolelist = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = rolelist;
            var userlist = context.Users.OrderBy(u => u.UserName).ToList().Select(uu =>
            new SelectListItem { Value = uu.UserName.ToString(), Text = uu.UserName }).ToList();
            ViewBag.Users = userlist;

            return View("Index");
        }
    }
}

FirmaTransportowa/FirmaTransportowa/FirmaTransportowa/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DomainModel;
using TransportDB;
using Microsoft.AspNet.Identity;
using FirmaTransportowa.Models;

namespace FirmaTransportowa.Controllers
{
    public class SchedulesController : Controller
    {
        private TransportDBContext db = new TransportDBContext();
        private ApplicationDbContext identityDb = new ApplicationDbContext();

        // GET: Schedules
        public ActionResult Index()
        {
            return View(db.Schedules.ToList());
        }

        // GET: Schedules/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // GET: Schedules/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Schedules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                //var _user = identityDb.Users.FirstOrDefault(x => x.Id.Equals(userId));

                schedule.UserId = userId;

                db.Schedules.Add(schedule);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(schedule);
        }

        // GET: Schedules/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // POST: Schedules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                db.Entry(schedule).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(schedule);
        }

        // GET: Schedules/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // POST: Schedules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Schedule schedule = db.Schedules.Find(id);
            db.Schedules.Remove(schedule);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult ChooseDriver()
        {
            var roleID = identityDb.Roles.Where(x => x.Name == "Driver").FirstOrDefault().Id;
            //var roleID = identityDb.Roles.OrderBy(r => r.Name).FirstOrDefault().Id;           
            var usersInRole = identityDb.Users.Where(m => m.Roles.Any(r => r.RoleId == roleID)).OrderBy(x => x.FirstName).ToList().
                Select(x => new SelectListItem { Value = x.Id, Text = x.FirstName + " " + x.LastName }).ToList();

            ViewBag.Drivers = usersInRole;

            return View();
        }

        public ActionResult DriverDetail(string Kierowca)
        {
            var schedule = db.Schedules.Where(x => x.UserId == Kierowca).FirstOrDefault();
            var user = identityDb.Users.Where(x => x.Id == Kierowca).Select(x => x.FirstName).ToString() + " "
                + identityDb.Users.Where(x => x.Id == Kierowca).Select(x => x.LastName).ToString();

            ViewBag.User = user;

            return View(schedule);
        }

        public ActionResult Back()
        {
            return RedirectToAction("ChooseDriver");
        }
    }
}

FirmaTransportowa/FirmaTransportowa/FirmaTransportowa/Views/Shared/_DropdownsPartial.cshtml
@{
    ViewBag.Title = "_DropdownsPartial";
}

@if (Request.IsAuthenticated && (User.IsInRole("Client") || User.IsInRole("Admin")))
{
    <ul class="nav navbar-nav justify-content-start">
        <li class="dropdown nav-item mr-auto">
            <a href="#" data-toggle="dropdown" role="button" aria-haspopup="true"
               aria-expanded="false" class="dropdown-toggle nav-link">Narzędzia<span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li class="dropdown-item">@Html.ActionLink("Moje rezerwacje", "ReservationHistory", "Reservations", null, new { @class = "dropdown-item" })</li>
                <li class="dropdown-item">@Html.ActionLink("Program lojalnościowy", "LoyalityProgram", "Home", null, new { @class = "dropdown-item" })</li>
                @*<li class="dropdown-item">Raporty</li>
                    <li class="dropdown-item">Dostawy</li>*@
            </ul>
        </li>
    </ul>
}

@if (Request.IsAuthenticated && (User.IsInRole("Driver") || User.IsInRole("Admin")))
{
    <ul class="nav navbar-nav justify-content-start">
        <li class="dropdown nav-item mr-auto">
            <a href="#" data-toggle="dropdown" role="button" aria-haspopup="true"
               aria-expanded="false" class="dropdown-toggle nav-link">Kierowcy<span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li class="dropdown-item">@Html.ActionLink("Dyspozycyjność", "Create", "Schedules", null, new { @class = "dropdown-item" })</li>
                <li class="dropdown-item">@Html.ActionLink("Utwórz raport", "Create", "Raports", null, new { @class = "dropdown-item" })</li>
                <li class="dropdown-item">@Html.ActionLink("Sprawdź rezerwacje", "List", "Reservations", null, new { @class = "dropdown-item" })</li>
            </ul>
        </li>
    </ul>
}

                            @if (Request.IsAuthenticated && (User.IsInRole("Secretary") || User.IsInRole("Admin")))
{
    <ul class="nav navbar-nav justify-content-start">
        <li class="dropdown nav-item mr-auto">
            <a href="#" data-toggle="dropdown" role="button" aria-haspopup="true"
               aria-expanded="false" class="dropdown-toggle nav-link">Sekretariat<span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li class="dropdown-item">@Html.ActionLink("Dyspozycyjność kierowców", "ChooseDriver", "Schedules", null, new { @class = "dropdown-item" })</li>
                <li class="dropdown-item">@Html.ActionLink("Raporty kierowców", "Index", "Raports", null, new { @class = "dropdown-item" })</li>
            </ul>
        </li>
    </ul>
}

@if (Request.IsAuthenticated && (User.IsInRole("Owner") || User.IsInRole("Admin")))
{
    <ul class="nav navbar-nav justify-content-start">
        <li class="dropdown nav-item mr-auto">
            <a href="#" data-toggle="dropdown" role="button" aria-haspopup="true"
               aria-expanded="false" class="dropdown-toggle nav-link">Narzędzia szefa<span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li class="dropdown-item">@Html.ActionLink("Role Manager", "Index", "Roles", null, new { @class = "dropdown-item" })</li>
                <li class="dropdown-item">
                    <a href="~/Areas/BusRoutes/RoutesList.aspx" class="dropdown-item">Zarządzanie trasami</a>
                </li>
            </ul>
        </li>
    </ul>
}

<ul class="nav navbar-nav justify-content-start">
    <li class="nav-item ml-auto">@Html.ActionLink("O firmie", "About", "Home", routeValues: null, htmlAttributes: new { @class = "nav-item nav-link" })</li>
</ul>

FirmaTransportowa/FirmaTransportowa/FirmaTransportowa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body background="~/Resources/bus.png" bgproperties="fixed">
    <div class="navbar navbar-inverse bg-inverse fixed-top navbar-toggleable-sm">
        <div class="container">
            <button type="button" class="navbar-toggler float-right hidden-md-up"
                    data-toggle="collapse" data-target=".navbar-collapse">
                ☰
            </button>
            @Html.ActionLink("DanPol", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            @Html.Partial("_DropdownsPartial")
            @Html.Partial("_LoginPartial")
        </div>
    </div>

    <div class="container body-content" style="margin-top:30px">
        @RenderBody()
    </div>

    <footer>

        <div class="container fixed-bottom">
            <div class="row">
                <div class="col-lg-12">
                    <p class="copyright text-muted small">Copyright &copy; Slamnation Web Design Studio 2017. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("style", required: false)
</body>
</html>